export type axieDetails = {
    from: number,
    size: number,
    sort: "PriceAsc" | "Latest",
    auctionType: "Sale",
    owner: null,
    criteria: {
    region: null,
    parts: string[] | null,
    bodyShapes: string[] | null,
    classes: string[] | null,
    stages: null,
    numMystic: null,
    pureness: null,
    title: null,
    breedable: null,
    breedCount: null,
    hp: [],
    skill: [],
    speed: [],
    morale: [],
    purity: [],
    numJapan: null,
    numXmas: null,
    numShiny: null,
    numSummer: null,
    ppBeast: null,
    ppAquatic: null,
    ppPlant: null,
    ppBug: null,
    ppBird: null,
    ppReptile: null,
    ppMech: null,
    ppDawn: null,
    ppDusk: null
    }
  }